package com.moneydesktop.finance.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.moneydesktop.finance.database.Category;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CATEGORY.
*/
public class CategoryDao extends AbstractDao<Category, Long> {

    public static final String TABLENAME = "CATEGORY";

    /**
     * Properties of entity Category.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CategoryName = new Property(1, String.class, "categoryName", false, "CATEGORY_NAME");
        public final static Property CategoryNumber = new Property(2, String.class, "categoryNumber", false, "CATEGORY_NUMBER");
        public final static Property ImageName = new Property(3, String.class, "imageName", false, "IMAGE_NAME");
        public final static Property IsSystem = new Property(4, Boolean.class, "isSystem", false, "IS_SYSTEM");
        public final static Property IsTaxRelated = new Property(5, Boolean.class, "isTaxRelated", false, "IS_TAX_RELATED");
        public final static Property Notes = new Property(6, String.class, "notes", false, "NOTES");
        public final static Property SortOrder = new Property(7, Integer.class, "sortOrder", false, "SORT_ORDER");
        public final static Property TaxReference = new Property(8, String.class, "taxReference", false, "TAX_REFERENCE");
        public final static Property CategoryTypeId = new Property(9, long.class, "categoryTypeId", false, "CATEGORY_TYPE_ID");
        public final static Property ParentCategoryId = new Property(10, long.class, "parentCategoryId", false, "PARENT_CATEGORY_ID");
    };

    private DaoSession daoSession;

    private Query<Category> categoryType_CategoriesQuery;
    private Query<Category> category_ChildrenQuery;

    public CategoryDao(DaoConfig config) {
        super(config);
    }
    
    public CategoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CATEGORY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CATEGORY_NAME' TEXT," + // 1: categoryName
                "'CATEGORY_NUMBER' TEXT," + // 2: categoryNumber
                "'IMAGE_NAME' TEXT," + // 3: imageName
                "'IS_SYSTEM' INTEGER," + // 4: isSystem
                "'IS_TAX_RELATED' INTEGER," + // 5: isTaxRelated
                "'NOTES' TEXT," + // 6: notes
                "'SORT_ORDER' INTEGER," + // 7: sortOrder
                "'TAX_REFERENCE' TEXT," + // 8: taxReference
                "'CATEGORY_TYPE_ID' INTEGER NOT NULL ," + // 9: categoryTypeId
                "'PARENT_CATEGORY_ID' INTEGER NOT NULL );"); // 10: parentCategoryId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CATEGORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Category entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String categoryName = entity.getCategoryName();
        if (categoryName != null) {
            stmt.bindString(2, categoryName);
        }
 
        String categoryNumber = entity.getCategoryNumber();
        if (categoryNumber != null) {
            stmt.bindString(3, categoryNumber);
        }
 
        String imageName = entity.getImageName();
        if (imageName != null) {
            stmt.bindString(4, imageName);
        }
 
        Boolean isSystem = entity.getIsSystem();
        if (isSystem != null) {
            stmt.bindLong(5, isSystem ? 1l: 0l);
        }
 
        Boolean isTaxRelated = entity.getIsTaxRelated();
        if (isTaxRelated != null) {
            stmt.bindLong(6, isTaxRelated ? 1l: 0l);
        }
 
        String notes = entity.getNotes();
        if (notes != null) {
            stmt.bindString(7, notes);
        }
 
        Integer sortOrder = entity.getSortOrder();
        if (sortOrder != null) {
            stmt.bindLong(8, sortOrder);
        }
 
        String taxReference = entity.getTaxReference();
        if (taxReference != null) {
            stmt.bindString(9, taxReference);
        }
        stmt.bindLong(10, entity.getCategoryTypeId());
        stmt.bindLong(11, entity.getParentCategoryId());
    }

    @Override
    protected void attachEntity(Category entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Category readEntity(Cursor cursor, int offset) {
        Category entity = new Category( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // categoryName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // categoryNumber
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // imageName
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isSystem
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // isTaxRelated
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // notes
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // sortOrder
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // taxReference
            cursor.getLong(offset + 9), // categoryTypeId
            cursor.getLong(offset + 10) // parentCategoryId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Category entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCategoryNumber(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImageName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsSystem(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setIsTaxRelated(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setNotes(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSortOrder(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setTaxReference(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCategoryTypeId(cursor.getLong(offset + 9));
        entity.setParentCategoryId(cursor.getLong(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Category entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Category entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "categories" to-many relationship of CategoryType. */
    public synchronized List<Category> _queryCategoryType_Categories(long categoryTypeId) {
        if (categoryType_CategoriesQuery == null) {
            QueryBuilder<Category> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.CategoryTypeId.eq(categoryTypeId));
            categoryType_CategoriesQuery = queryBuilder.build();
        } else {
            categoryType_CategoriesQuery.setParameter(0, categoryTypeId);
        }
        return categoryType_CategoriesQuery.list();
    }

    /** Internal query to resolve the "children" to-many relationship of Category. */
    public synchronized List<Category> _queryCategory_Children(long parentCategoryId) {
        if (category_ChildrenQuery == null) {
            QueryBuilder<Category> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.ParentCategoryId.eq(parentCategoryId));
            category_ChildrenQuery = queryBuilder.build();
        } else {
            category_ChildrenQuery.setParameter(0, parentCategoryId);
        }
        return category_ChildrenQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCategoryTypeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCategoryDao().getAllColumns());
            builder.append(" FROM CATEGORY T");
            builder.append(" LEFT JOIN CATEGORY_TYPE T0 ON T.'CATEGORY_TYPE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN CATEGORY T1 ON T.'PARENT_CATEGORY_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Category loadCurrentDeep(Cursor cursor, boolean lock) {
        Category entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CategoryType categoryType = loadCurrentOther(daoSession.getCategoryTypeDao(), cursor, offset);
         if(categoryType != null) {
            entity.setCategoryType(categoryType);
        }
        offset += daoSession.getCategoryTypeDao().getAllColumns().length;

        Category parent = loadCurrentOther(daoSession.getCategoryDao(), cursor, offset);
         if(parent != null) {
            entity.setParent(parent);
        }

        return entity;    
    }

    public Category loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Category> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Category> list = new ArrayList<Category>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Category> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Category> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
