package com.moneydesktop.finance.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.moneydesktop.finance.database.Transaction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TRANSACTION.
*/
public class TransactionDao extends AbstractDao<Transaction, Long> {

    public static final String TABLENAME = "TRANSACTION";

    /**
     * Properties of entity Transaction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Amount = new Property(1, Double.class, "amount", false, "AMOUNT");
        public final static Property AmountReimbursable = new Property(2, Double.class, "amountReimbursable", false, "AMOUNT_REIMBURSABLE");
        public final static Property ClassId = new Property(3, String.class, "classId", false, "CLASS_ID");
        public final static Property Date = new Property(4, java.util.Date.class, "date", false, "DATE");
        public final static Property DatePosted = new Property(5, java.util.Date.class, "datePosted", false, "DATE_POSTED");
        public final static Property DayNumber = new Property(6, Integer.class, "dayNumber", false, "DAY_NUMBER");
        public final static Property ExclusionFlags = new Property(7, Integer.class, "exclusionFlags", false, "EXCLUSION_FLAGS");
        public final static Property HasReceipt = new Property(8, Boolean.class, "hasReceipt", false, "HAS_RECEIPT");
        public final static Property HasSplit = new Property(9, Boolean.class, "hasSplit", false, "HAS_SPLIT");
        public final static Property IsBusiness = new Property(10, Boolean.class, "isBusiness", false, "IS_BUSINESS");
        public final static Property IsCleared = new Property(11, Boolean.class, "isCleared", false, "IS_CLEARED");
        public final static Property IsExcluded = new Property(12, Boolean.class, "isExcluded", false, "IS_EXCLUDED");
        public final static Property IsFlagged = new Property(13, Boolean.class, "isFlagged", false, "IS_FLAGGED");
        public final static Property IsManual = new Property(14, Boolean.class, "isManual", false, "IS_MANUAL");
        public final static Property IsMatched = new Property(15, Boolean.class, "isMatched", false, "IS_MATCHED");
        public final static Property IsProcessed = new Property(16, Boolean.class, "isProcessed", false, "IS_PROCESSED");
        public final static Property IsReimbursable = new Property(17, Boolean.class, "isReimbursable", false, "IS_REIMBURSABLE");
        public final static Property IsReported = new Property(18, Boolean.class, "isReported", false, "IS_REPORTED");
        public final static Property IsReportedAndPaid = new Property(19, Boolean.class, "isReportedAndPaid", false, "IS_REPORTED_AND_PAID");
        public final static Property IsReportedAndSubmitted = new Property(20, Boolean.class, "isReportedAndSubmitted", false, "IS_REPORTED_AND_SUBMITTED");
        public final static Property IsSplit = new Property(21, Boolean.class, "isSplit", false, "IS_SPLIT");
        public final static Property IsVoid = new Property(22, Boolean.class, "isVoid", false, "IS_VOID");
        public final static Property Memo = new Property(23, String.class, "memo", false, "MEMO");
        public final static Property MonthName = new Property(24, String.class, "monthName", false, "MONTH_NAME");
        public final static Property MonthNumber = new Property(25, Integer.class, "monthNumber", false, "MONTH_NUMBER");
        public final static Property NormalizedAmount = new Property(26, Double.class, "normalizedAmount", false, "NORMALIZED_AMOUNT");
        public final static Property OriginalCategory = new Property(27, String.class, "originalCategory", false, "ORIGINAL_CATEGORY");
        public final static Property OriginalTitle = new Property(28, String.class, "originalTitle", false, "ORIGINAL_TITLE");
        public final static Property QuarterNumber = new Property(29, Integer.class, "quarterNumber", false, "QUARTER_NUMBER");
        public final static Property RawAmount = new Property(30, Double.class, "rawAmount", false, "RAW_AMOUNT");
        public final static Property Reference = new Property(31, String.class, "reference", false, "REFERENCE");
        public final static Property TagString = new Property(32, String.class, "tagString", false, "TAG_STRING");
        public final static Property Title = new Property(33, String.class, "title", false, "TITLE");
        public final static Property TransactionType = new Property(34, Integer.class, "transactionType", false, "TRANSACTION_TYPE");
        public final static Property WeekNumber = new Property(35, Integer.class, "weekNumber", false, "WEEK_NUMBER");
        public final static Property YearNumber = new Property(36, Integer.class, "yearNumber", false, "YEAR_NUMBER");
        public final static Property BankAccountId = new Property(37, long.class, "bankAccountId", false, "BANK_ACCOUNT_ID");
        public final static Property CategoryId = new Property(38, long.class, "categoryId", false, "CATEGORY_ID");
        public final static Property ParentTransactionId = new Property(39, long.class, "parentTransactionId", false, "PARENT_TRANSACTION_ID");
    };

    private DaoSession daoSession;

    private Query<Transaction> bankAccount_TransactionsQuery;
    private Query<Transaction> category_TransactionsQuery;
    private Query<Transaction> transaction_ChildrenQuery;

    public TransactionDao(DaoConfig config) {
        super(config);
    }
    
    public TransactionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TRANSACTION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'AMOUNT' REAL," + // 1: amount
                "'AMOUNT_REIMBURSABLE' REAL," + // 2: amountReimbursable
                "'CLASS_ID' TEXT," + // 3: classId
                "'DATE' INTEGER," + // 4: date
                "'DATE_POSTED' INTEGER," + // 5: datePosted
                "'DAY_NUMBER' INTEGER," + // 6: dayNumber
                "'EXCLUSION_FLAGS' INTEGER," + // 7: exclusionFlags
                "'HAS_RECEIPT' INTEGER," + // 8: hasReceipt
                "'HAS_SPLIT' INTEGER," + // 9: hasSplit
                "'IS_BUSINESS' INTEGER," + // 10: isBusiness
                "'IS_CLEARED' INTEGER," + // 11: isCleared
                "'IS_EXCLUDED' INTEGER," + // 12: isExcluded
                "'IS_FLAGGED' INTEGER," + // 13: isFlagged
                "'IS_MANUAL' INTEGER," + // 14: isManual
                "'IS_MATCHED' INTEGER," + // 15: isMatched
                "'IS_PROCESSED' INTEGER," + // 16: isProcessed
                "'IS_REIMBURSABLE' INTEGER," + // 17: isReimbursable
                "'IS_REPORTED' INTEGER," + // 18: isReported
                "'IS_REPORTED_AND_PAID' INTEGER," + // 19: isReportedAndPaid
                "'IS_REPORTED_AND_SUBMITTED' INTEGER," + // 20: isReportedAndSubmitted
                "'IS_SPLIT' INTEGER," + // 21: isSplit
                "'IS_VOID' INTEGER," + // 22: isVoid
                "'MEMO' TEXT," + // 23: memo
                "'MONTH_NAME' TEXT," + // 24: monthName
                "'MONTH_NUMBER' INTEGER," + // 25: monthNumber
                "'NORMALIZED_AMOUNT' REAL," + // 26: normalizedAmount
                "'ORIGINAL_CATEGORY' TEXT," + // 27: originalCategory
                "'ORIGINAL_TITLE' TEXT," + // 28: originalTitle
                "'QUARTER_NUMBER' INTEGER," + // 29: quarterNumber
                "'RAW_AMOUNT' REAL," + // 30: rawAmount
                "'REFERENCE' TEXT," + // 31: reference
                "'TAG_STRING' TEXT," + // 32: tagString
                "'TITLE' TEXT," + // 33: title
                "'TRANSACTION_TYPE' INTEGER," + // 34: transactionType
                "'WEEK_NUMBER' INTEGER," + // 35: weekNumber
                "'YEAR_NUMBER' INTEGER," + // 36: yearNumber
                "'BANK_ACCOUNT_ID' INTEGER NOT NULL ," + // 37: bankAccountId
                "'CATEGORY_ID' INTEGER NOT NULL ," + // 38: categoryId
                "'PARENT_TRANSACTION_ID' INTEGER NOT NULL );"); // 39: parentTransactionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TRANSACTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Transaction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double amount = entity.getAmount();
        if (amount != null) {
            stmt.bindDouble(2, amount);
        }
 
        Double amountReimbursable = entity.getAmountReimbursable();
        if (amountReimbursable != null) {
            stmt.bindDouble(3, amountReimbursable);
        }
 
        String classId = entity.getClassId();
        if (classId != null) {
            stmt.bindString(4, classId);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(5, date.getTime());
        }
 
        java.util.Date datePosted = entity.getDatePosted();
        if (datePosted != null) {
            stmt.bindLong(6, datePosted.getTime());
        }
 
        Integer dayNumber = entity.getDayNumber();
        if (dayNumber != null) {
            stmt.bindLong(7, dayNumber);
        }
 
        Integer exclusionFlags = entity.getExclusionFlags();
        if (exclusionFlags != null) {
            stmt.bindLong(8, exclusionFlags);
        }
 
        Boolean hasReceipt = entity.getHasReceipt();
        if (hasReceipt != null) {
            stmt.bindLong(9, hasReceipt ? 1l: 0l);
        }
 
        Boolean hasSplit = entity.getHasSplit();
        if (hasSplit != null) {
            stmt.bindLong(10, hasSplit ? 1l: 0l);
        }
 
        Boolean isBusiness = entity.getIsBusiness();
        if (isBusiness != null) {
            stmt.bindLong(11, isBusiness ? 1l: 0l);
        }
 
        Boolean isCleared = entity.getIsCleared();
        if (isCleared != null) {
            stmt.bindLong(12, isCleared ? 1l: 0l);
        }
 
        Boolean isExcluded = entity.getIsExcluded();
        if (isExcluded != null) {
            stmt.bindLong(13, isExcluded ? 1l: 0l);
        }
 
        Boolean isFlagged = entity.getIsFlagged();
        if (isFlagged != null) {
            stmt.bindLong(14, isFlagged ? 1l: 0l);
        }
 
        Boolean isManual = entity.getIsManual();
        if (isManual != null) {
            stmt.bindLong(15, isManual ? 1l: 0l);
        }
 
        Boolean isMatched = entity.getIsMatched();
        if (isMatched != null) {
            stmt.bindLong(16, isMatched ? 1l: 0l);
        }
 
        Boolean isProcessed = entity.getIsProcessed();
        if (isProcessed != null) {
            stmt.bindLong(17, isProcessed ? 1l: 0l);
        }
 
        Boolean isReimbursable = entity.getIsReimbursable();
        if (isReimbursable != null) {
            stmt.bindLong(18, isReimbursable ? 1l: 0l);
        }
 
        Boolean isReported = entity.getIsReported();
        if (isReported != null) {
            stmt.bindLong(19, isReported ? 1l: 0l);
        }
 
        Boolean isReportedAndPaid = entity.getIsReportedAndPaid();
        if (isReportedAndPaid != null) {
            stmt.bindLong(20, isReportedAndPaid ? 1l: 0l);
        }
 
        Boolean isReportedAndSubmitted = entity.getIsReportedAndSubmitted();
        if (isReportedAndSubmitted != null) {
            stmt.bindLong(21, isReportedAndSubmitted ? 1l: 0l);
        }
 
        Boolean isSplit = entity.getIsSplit();
        if (isSplit != null) {
            stmt.bindLong(22, isSplit ? 1l: 0l);
        }
 
        Boolean isVoid = entity.getIsVoid();
        if (isVoid != null) {
            stmt.bindLong(23, isVoid ? 1l: 0l);
        }
 
        String memo = entity.getMemo();
        if (memo != null) {
            stmt.bindString(24, memo);
        }
 
        String monthName = entity.getMonthName();
        if (monthName != null) {
            stmt.bindString(25, monthName);
        }
 
        Integer monthNumber = entity.getMonthNumber();
        if (monthNumber != null) {
            stmt.bindLong(26, monthNumber);
        }
 
        Double normalizedAmount = entity.getNormalizedAmount();
        if (normalizedAmount != null) {
            stmt.bindDouble(27, normalizedAmount);
        }
 
        String originalCategory = entity.getOriginalCategory();
        if (originalCategory != null) {
            stmt.bindString(28, originalCategory);
        }
 
        String originalTitle = entity.getOriginalTitle();
        if (originalTitle != null) {
            stmt.bindString(29, originalTitle);
        }
 
        Integer quarterNumber = entity.getQuarterNumber();
        if (quarterNumber != null) {
            stmt.bindLong(30, quarterNumber);
        }
 
        Double rawAmount = entity.getRawAmount();
        if (rawAmount != null) {
            stmt.bindDouble(31, rawAmount);
        }
 
        String reference = entity.getReference();
        if (reference != null) {
            stmt.bindString(32, reference);
        }
 
        String tagString = entity.getTagString();
        if (tagString != null) {
            stmt.bindString(33, tagString);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(34, title);
        }
 
        Integer transactionType = entity.getTransactionType();
        if (transactionType != null) {
            stmt.bindLong(35, transactionType);
        }
 
        Integer weekNumber = entity.getWeekNumber();
        if (weekNumber != null) {
            stmt.bindLong(36, weekNumber);
        }
 
        Integer yearNumber = entity.getYearNumber();
        if (yearNumber != null) {
            stmt.bindLong(37, yearNumber);
        }
        stmt.bindLong(38, entity.getBankAccountId());
        stmt.bindLong(39, entity.getCategoryId());
        stmt.bindLong(40, entity.getParentTransactionId());
    }

    @Override
    protected void attachEntity(Transaction entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Transaction readEntity(Cursor cursor, int offset) {
        Transaction entity = new Transaction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // amount
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // amountReimbursable
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // classId
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // date
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // datePosted
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // dayNumber
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // exclusionFlags
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // hasReceipt
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // hasSplit
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0, // isBusiness
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0, // isCleared
            cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0, // isExcluded
            cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0, // isFlagged
            cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0, // isManual
            cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0, // isMatched
            cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0, // isProcessed
            cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0, // isReimbursable
            cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0, // isReported
            cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0, // isReportedAndPaid
            cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0, // isReportedAndSubmitted
            cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0, // isSplit
            cursor.isNull(offset + 22) ? null : cursor.getShort(offset + 22) != 0, // isVoid
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // memo
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // monthName
            cursor.isNull(offset + 25) ? null : cursor.getInt(offset + 25), // monthNumber
            cursor.isNull(offset + 26) ? null : cursor.getDouble(offset + 26), // normalizedAmount
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // originalCategory
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // originalTitle
            cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29), // quarterNumber
            cursor.isNull(offset + 30) ? null : cursor.getDouble(offset + 30), // rawAmount
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // reference
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // tagString
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // title
            cursor.isNull(offset + 34) ? null : cursor.getInt(offset + 34), // transactionType
            cursor.isNull(offset + 35) ? null : cursor.getInt(offset + 35), // weekNumber
            cursor.isNull(offset + 36) ? null : cursor.getInt(offset + 36), // yearNumber
            cursor.getLong(offset + 37), // bankAccountId
            cursor.getLong(offset + 38), // categoryId
            cursor.getLong(offset + 39) // parentTransactionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Transaction entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAmount(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setAmountReimbursable(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setClassId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDate(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setDatePosted(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setDayNumber(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setExclusionFlags(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setHasReceipt(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setHasSplit(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setIsBusiness(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
        entity.setIsCleared(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
        entity.setIsExcluded(cursor.isNull(offset + 12) ? null : cursor.getShort(offset + 12) != 0);
        entity.setIsFlagged(cursor.isNull(offset + 13) ? null : cursor.getShort(offset + 13) != 0);
        entity.setIsManual(cursor.isNull(offset + 14) ? null : cursor.getShort(offset + 14) != 0);
        entity.setIsMatched(cursor.isNull(offset + 15) ? null : cursor.getShort(offset + 15) != 0);
        entity.setIsProcessed(cursor.isNull(offset + 16) ? null : cursor.getShort(offset + 16) != 0);
        entity.setIsReimbursable(cursor.isNull(offset + 17) ? null : cursor.getShort(offset + 17) != 0);
        entity.setIsReported(cursor.isNull(offset + 18) ? null : cursor.getShort(offset + 18) != 0);
        entity.setIsReportedAndPaid(cursor.isNull(offset + 19) ? null : cursor.getShort(offset + 19) != 0);
        entity.setIsReportedAndSubmitted(cursor.isNull(offset + 20) ? null : cursor.getShort(offset + 20) != 0);
        entity.setIsSplit(cursor.isNull(offset + 21) ? null : cursor.getShort(offset + 21) != 0);
        entity.setIsVoid(cursor.isNull(offset + 22) ? null : cursor.getShort(offset + 22) != 0);
        entity.setMemo(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setMonthName(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setMonthNumber(cursor.isNull(offset + 25) ? null : cursor.getInt(offset + 25));
        entity.setNormalizedAmount(cursor.isNull(offset + 26) ? null : cursor.getDouble(offset + 26));
        entity.setOriginalCategory(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setOriginalTitle(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setQuarterNumber(cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29));
        entity.setRawAmount(cursor.isNull(offset + 30) ? null : cursor.getDouble(offset + 30));
        entity.setReference(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTagString(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTitle(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setTransactionType(cursor.isNull(offset + 34) ? null : cursor.getInt(offset + 34));
        entity.setWeekNumber(cursor.isNull(offset + 35) ? null : cursor.getInt(offset + 35));
        entity.setYearNumber(cursor.isNull(offset + 36) ? null : cursor.getInt(offset + 36));
        entity.setBankAccountId(cursor.getLong(offset + 37));
        entity.setCategoryId(cursor.getLong(offset + 38));
        entity.setParentTransactionId(cursor.getLong(offset + 39));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Transaction entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Transaction entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "transactions" to-many relationship of BankAccount. */
    public synchronized List<Transaction> _queryBankAccount_Transactions(long bankAccountId) {
        if (bankAccount_TransactionsQuery == null) {
            QueryBuilder<Transaction> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.BankAccountId.eq(bankAccountId));
            bankAccount_TransactionsQuery = queryBuilder.build();
        } else {
            bankAccount_TransactionsQuery.setParameter(0, bankAccountId);
        }
        return bankAccount_TransactionsQuery.list();
    }

    /** Internal query to resolve the "transactions" to-many relationship of Category. */
    public synchronized List<Transaction> _queryCategory_Transactions(long categoryId) {
        if (category_TransactionsQuery == null) {
            QueryBuilder<Transaction> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.CategoryId.eq(categoryId));
            category_TransactionsQuery = queryBuilder.build();
        } else {
            category_TransactionsQuery.setParameter(0, categoryId);
        }
        return category_TransactionsQuery.list();
    }

    /** Internal query to resolve the "children" to-many relationship of Transaction. */
    public synchronized List<Transaction> _queryTransaction_Children(long parentTransactionId) {
        if (transaction_ChildrenQuery == null) {
            QueryBuilder<Transaction> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.ParentTransactionId.eq(parentTransactionId));
            transaction_ChildrenQuery = queryBuilder.build();
        } else {
            transaction_ChildrenQuery.setParameter(0, parentTransactionId);
        }
        return transaction_ChildrenQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBankAccountDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getCategoryDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getTransactionDao().getAllColumns());
            builder.append(" FROM TRANSACTION T");
            builder.append(" LEFT JOIN BANK_ACCOUNT T0 ON T.'BANK_ACCOUNT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN CATEGORY T1 ON T.'CATEGORY_ID'=T1.'_id'");
            builder.append(" LEFT JOIN TRANSACTION T2 ON T.'PARENT_TRANSACTION_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Transaction loadCurrentDeep(Cursor cursor, boolean lock) {
        Transaction entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BankAccount bankAccount = loadCurrentOther(daoSession.getBankAccountDao(), cursor, offset);
         if(bankAccount != null) {
            entity.setBankAccount(bankAccount);
        }
        offset += daoSession.getBankAccountDao().getAllColumns().length;

        Category category = loadCurrentOther(daoSession.getCategoryDao(), cursor, offset);
         if(category != null) {
            entity.setCategory(category);
        }
        offset += daoSession.getCategoryDao().getAllColumns().length;

        Transaction parent = loadCurrentOther(daoSession.getTransactionDao(), cursor, offset);
         if(parent != null) {
            entity.setParent(parent);
        }

        return entity;    
    }

    public Transaction loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Transaction> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Transaction> list = new ArrayList<Transaction>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Transaction> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Transaction> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
