package com.moneydesktop.finance.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.moneydesktop.finance.database.BankAccountBalance;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BANK_ACCOUNT_BALANCE.
*/
public class BankAccountBalanceDao extends AbstractDao<BankAccountBalance, Long> {

    public static final String TABLENAME = "BANK_ACCOUNT_BALANCE";

    /**
     * Properties of entity BankAccountBalance.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Balance = new Property(1, Double.class, "balance", false, "BALANCE");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property BusinessObjectId = new Property(3, long.class, "businessObjectId", false, "BUSINESS_OBJECT_ID");
        public final static Property BankAccountId = new Property(4, Long.class, "bankAccountId", false, "BANK_ACCOUNT_ID");
    };

    private DaoSession daoSession;

    private Query<BankAccountBalance> bankAccount_BankAccountBalancesQuery;

    public BankAccountBalanceDao(DaoConfig config) {
        super(config);
    }
    
    public BankAccountBalanceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BANK_ACCOUNT_BALANCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'BALANCE' REAL," + // 1: balance
                "'DATE' INTEGER," + // 2: date
                "'BUSINESS_OBJECT_ID' INTEGER NOT NULL ," + // 3: businessObjectId
                "'BANK_ACCOUNT_ID' INTEGER);"); // 4: bankAccountId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BANK_ACCOUNT_BALANCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BankAccountBalance entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double balance = entity.getBalance();
        if (balance != null) {
            stmt.bindDouble(2, balance);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
        stmt.bindLong(4, entity.getBusinessObjectId());
 
        Long bankAccountId = entity.getBankAccountId();
        if (bankAccountId != null) {
            stmt.bindLong(5, bankAccountId);
        }
    }

    @Override
    protected void attachEntity(BankAccountBalance entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BankAccountBalance readEntity(Cursor cursor, int offset) {
        BankAccountBalance entity = new BankAccountBalance( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // balance
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // date
            cursor.getLong(offset + 3), // businessObjectId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // bankAccountId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BankAccountBalance entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBalance(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setBusinessObjectId(cursor.getLong(offset + 3));
        entity.setBankAccountId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BankAccountBalance entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BankAccountBalance entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "bankAccountBalances" to-many relationship of BankAccount. */
    public List<BankAccountBalance> _queryBankAccount_BankAccountBalances(Long bankAccountId) {
        synchronized (this) {
            if (bankAccount_BankAccountBalancesQuery == null) {
                QueryBuilder<BankAccountBalance> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.BankAccountId.eq(null));
                bankAccount_BankAccountBalancesQuery = queryBuilder.build();
            }
        }
        Query<BankAccountBalance> query = bankAccount_BankAccountBalancesQuery.forCurrentThread();
        query.setParameter(0, bankAccountId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBusinessObjectBaseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBankAccountDao().getAllColumns());
            builder.append(" FROM BANK_ACCOUNT_BALANCE T");
            builder.append(" LEFT JOIN BUSINESS_OBJECT_BASE T0 ON T.'BUSINESS_OBJECT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN BANK_ACCOUNT T1 ON T.'BANK_ACCOUNT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BankAccountBalance loadCurrentDeep(Cursor cursor, boolean lock) {
        BankAccountBalance entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BusinessObjectBase businessObjectBase = loadCurrentOther(daoSession.getBusinessObjectBaseDao(), cursor, offset);
         if(businessObjectBase != null) {
            entity.setBusinessObjectBase(businessObjectBase);
        }
        offset += daoSession.getBusinessObjectBaseDao().getAllColumns().length;

        BankAccount bankAccount = loadCurrentOther(daoSession.getBankAccountDao(), cursor, offset);
        entity.setBankAccount(bankAccount);

        return entity;    
    }

    public BankAccountBalance loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BankAccountBalance> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BankAccountBalance> list = new ArrayList<BankAccountBalance>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BankAccountBalance> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BankAccountBalance> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
