package com.moneydesktop.finance.database;

import com.moneydesktop.finance.database.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TAG_INSTANCE.
 */
public class TagInstance extends BusinessObject  {

    private Long id;
    private long tagId;
    private long buinessObjectId;
    private long businessObjectId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TagInstanceDao myDao;

    private Tag tag;
    private Long tag__resolvedKey;

    private BusinessObjectBase businessObject;
    private Long businessObject__resolvedKey;

    private BusinessObjectBase businessObjectBase;
    private Long businessObjectBase__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TagInstance() {
    }

    public TagInstance(Long id) {
        this.id = id;
    }

    public TagInstance(Long id, long tagId, long buinessObjectId, long businessObjectId) {
        this.id = id;
        this.tagId = tagId;
        this.buinessObjectId = buinessObjectId;
        this.businessObjectId = businessObjectId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTagInstanceDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTagId() {
        return tagId;
    }

    public void setTagId(long tagId) {
        this.tagId = tagId;
    }

    public long getBuinessObjectId() {
        return buinessObjectId;
    }

    public void setBuinessObjectId(long buinessObjectId) {
        this.buinessObjectId = buinessObjectId;
    }

    public long getBusinessObjectId() {
        return businessObjectId;
    }

    public void setBusinessObjectId(long businessObjectId) {
        this.businessObjectId = businessObjectId;
    }

    /** To-one relationship, resolved on first access. */
    public Tag getTag() {
        if (tag__resolvedKey == null || !tag__resolvedKey.equals(tagId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            TagDao targetDao = daoSession.getTagDao();
            tag = targetDao.load(tagId);
            tag__resolvedKey = tagId;
        }
        return tag;
    }

    public void setTag(Tag tag) {
        if (tag == null) {
            throw new DaoException("To-one property 'tagId' has not-null constraint; cannot set to-one to null");
        }
        this.tag = tag;
        tagId = tag.getId();
        tag__resolvedKey = tagId;
    }

    /** To-one relationship, resolved on first access. */
    public BusinessObjectBase getBusinessObject() {
        if (businessObject__resolvedKey == null || !businessObject__resolvedKey.equals(buinessObjectId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BusinessObjectBaseDao targetDao = daoSession.getBusinessObjectBaseDao();
            businessObject = targetDao.load(buinessObjectId);
            businessObject__resolvedKey = buinessObjectId;
        }
        return businessObject;
    }

    public void setBusinessObject(BusinessObjectBase businessObject) {
        if (businessObject == null) {
            throw new DaoException("To-one property 'buinessObjectId' has not-null constraint; cannot set to-one to null");
        }
        this.businessObject = businessObject;
        buinessObjectId = businessObject.getId();
        businessObject__resolvedKey = buinessObjectId;
    }

    /** To-one relationship, resolved on first access. */
    public BusinessObjectBase getBusinessObjectBase() {
        if (businessObjectBase__resolvedKey == null || !businessObjectBase__resolvedKey.equals(businessObjectId)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BusinessObjectBaseDao targetDao = daoSession.getBusinessObjectBaseDao();
            businessObjectBase = targetDao.load(businessObjectId);
            businessObjectBase__resolvedKey = businessObjectId;
        }
        return businessObjectBase;
    }

    public void setBusinessObjectBase(BusinessObjectBase businessObjectBase) {
        if (businessObjectBase == null) {
            throw new DaoException("To-one property 'businessObjectId' has not-null constraint; cannot set to-one to null");
        }
        this.businessObjectBase = businessObjectBase;
        businessObjectId = businessObjectBase.getId();
        businessObjectBase__resolvedKey = businessObjectId;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    
    public void setExternalId(String id) {
    	
    }
    
    public String getExternalId() {
    	return "";
    }
    
    public static TagInstance createTagInstance(BusinessObjectBase bob, Tag tag) {
    	
    	TagInstance tagInstance = new TagInstance();
    	tagInstance.setTag(tag);
    	tagInstance.setBusinessObjectBase(bob);
    	
    	tagInstance.insertBatch();
    	
    	return tagInstance;
    }
    // KEEP METHODS END

}
