package com.moneydesktop.finance.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;
import de.greenrobot.dao.Query;
import de.greenrobot.dao.QueryBuilder;

import com.moneydesktop.finance.database.TagInstance;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TAG_INSTANCE.
*/
public class TagInstanceDao extends AbstractDao<TagInstance, Long> {

    public static final String TABLENAME = "TAG_INSTANCE";

    /**
     * Properties of entity TagInstance.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TagId = new Property(1, long.class, "tagId", false, "TAG_ID");
        public final static Property BaseObjectId = new Property(2, long.class, "baseObjectId", false, "BASE_OBJECT_ID");
        public final static Property BusinessObjectId = new Property(3, long.class, "businessObjectId", false, "BUSINESS_OBJECT_ID");
    };

    private DaoSession daoSession;

    private Query<TagInstance> businessObjectBase_TagInstancesQuery;
    private Query<TagInstance> tag_TagInstancesQuery;

    public TagInstanceDao(DaoConfig config) {
        super(config);
    }
    
    public TagInstanceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TAG_INSTANCE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'TAG_ID' INTEGER NOT NULL ," + // 1: tagId
                "'BASE_OBJECT_ID' INTEGER NOT NULL ," + // 2: baseObjectId
                "'BUSINESS_OBJECT_ID' INTEGER NOT NULL );"); // 3: businessObjectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TAG_INSTANCE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TagInstance entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTagId());
        stmt.bindLong(3, entity.getBaseObjectId());
        stmt.bindLong(4, entity.getBusinessObjectId());
    }

    @Override
    protected void attachEntity(TagInstance entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TagInstance readEntity(Cursor cursor, int offset) {
        TagInstance entity = new TagInstance( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // tagId
            cursor.getLong(offset + 2), // baseObjectId
            cursor.getLong(offset + 3) // businessObjectId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TagInstance entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTagId(cursor.getLong(offset + 1));
        entity.setBaseObjectId(cursor.getLong(offset + 2));
        entity.setBusinessObjectId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TagInstance entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TagInstance entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tagInstances" to-many relationship of BusinessObjectBase. */
    public synchronized List<TagInstance> _queryBusinessObjectBase_TagInstances(long baseObjectId) {
        if (businessObjectBase_TagInstancesQuery == null) {
            QueryBuilder<TagInstance> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.BaseObjectId.eq(baseObjectId));
            businessObjectBase_TagInstancesQuery = queryBuilder.build();
        } else {
            businessObjectBase_TagInstancesQuery.setParameter(0, baseObjectId);
        }
        return businessObjectBase_TagInstancesQuery.list();
    }

    /** Internal query to resolve the "tagInstances" to-many relationship of Tag. */
    public synchronized List<TagInstance> _queryTag_TagInstances(long tagId) {
        if (tag_TagInstancesQuery == null) {
            QueryBuilder<TagInstance> queryBuilder = queryBuilder();
            queryBuilder.where(Properties.TagId.eq(tagId));
            tag_TagInstancesQuery = queryBuilder.build();
        } else {
            tag_TagInstancesQuery.setParameter(0, tagId);
        }
        return tag_TagInstancesQuery.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTagDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBusinessObjectBaseDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getBusinessObjectBaseDao().getAllColumns());
            builder.append(" FROM TAG_INSTANCE T");
            builder.append(" LEFT JOIN TAG T0 ON T.'TAG_ID'=T0.'_id'");
            builder.append(" LEFT JOIN BUSINESS_OBJECT_BASE T1 ON T.'BASE_OBJECT_ID'=T1.'_id'");
            builder.append(" LEFT JOIN BUSINESS_OBJECT_BASE T2 ON T.'BUSINESS_OBJECT_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TagInstance loadCurrentDeep(Cursor cursor, boolean lock) {
        TagInstance entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Tag tag = loadCurrentOther(daoSession.getTagDao(), cursor, offset);
         if(tag != null) {
            entity.setTag(tag);
        }
        offset += daoSession.getTagDao().getAllColumns().length;

        BusinessObjectBase businessObject = loadCurrentOther(daoSession.getBusinessObjectBaseDao(), cursor, offset);
         if(businessObject != null) {
            entity.setBusinessObject(businessObject);
        }
        offset += daoSession.getBusinessObjectBaseDao().getAllColumns().length;

        BusinessObjectBase businessObjectBase = loadCurrentOther(daoSession.getBusinessObjectBaseDao(), cursor, offset);
         if(businessObjectBase != null) {
            entity.setBusinessObjectBase(businessObjectBase);
        }

        return entity;    
    }

    public TagInstance loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TagInstance> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TagInstance> list = new ArrayList<TagInstance>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TagInstance> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TagInstance> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
