package main.java.com.moneydesktop.finance.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import main.java.com.moneydesktop.finance.database.CategoryType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table CATEGORY_TYPE.
*/
public class CategoryTypeDao extends AbstractDao<CategoryType, Long> {

    public static final String TABLENAME = "CATEGORY_TYPE";

    /**
     * Properties of entity CategoryType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CategoryTypeId = new Property(1, String.class, "categoryTypeId", false, "CATEGORY_TYPE_ID");
        public final static Property CategoryTypeName = new Property(2, String.class, "categoryTypeName", false, "CATEGORY_TYPE_NAME");
        public final static Property BusinessObjectId = new Property(3, long.class, "businessObjectId", false, "BUSINESS_OBJECT_ID");
    };

    private DaoSession daoSession;


    public CategoryTypeDao(DaoConfig config) {
        super(config);
    }

    public CategoryTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CATEGORY_TYPE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CATEGORY_TYPE_ID' TEXT," + // 1: categoryTypeId
                "'CATEGORY_TYPE_NAME' TEXT," + // 2: categoryTypeName
                "'BUSINESS_OBJECT_ID' INTEGER NOT NULL );"); // 3: businessObjectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CATEGORY_TYPE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CategoryType entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String categoryTypeId = entity.getCategoryTypeId();
        if (categoryTypeId != null) {
            stmt.bindString(2, categoryTypeId);
        }

        String categoryTypeName = entity.getCategoryTypeName();
        if (categoryTypeName != null) {
            stmt.bindString(3, categoryTypeName);
        }
        stmt.bindLong(4, entity.getBusinessObjectId());
    }

    @Override
    protected void attachEntity(CategoryType entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public CategoryType readEntity(Cursor cursor, int offset) {
        CategoryType entity = new CategoryType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // categoryTypeId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // categoryTypeName
            cursor.getLong(offset + 3) // businessObjectId
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CategoryType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCategoryTypeId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCategoryTypeName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBusinessObjectId(cursor.getLong(offset + 3));
     }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CategoryType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(CategoryType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBusinessObjectBaseDao().getAllColumns());
            builder.append(" FROM CATEGORY_TYPE T");
            builder.append(" LEFT JOIN BUSINESS_OBJECT_BASE T0 ON T.'BUSINESS_OBJECT_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }

    protected CategoryType loadCurrentDeep(Cursor cursor, boolean lock) {
        CategoryType entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BusinessObjectBase businessObjectBase = loadCurrentOther(daoSession.getBusinessObjectBaseDao(), cursor, offset);
         if(businessObjectBase != null) {
            entity.setBusinessObjectBase(businessObjectBase);
        }

        return entity;
    }

    public CategoryType loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();

        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);

        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }

    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CategoryType> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CategoryType> list = new ArrayList<CategoryType>(count);

        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }

    protected List<CategoryType> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }


    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CategoryType> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }

}
